# **ISL League Table Predictions**

## **Initials**

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
data_ = pd.read_csv('/content/ISL ML - Sheet1.csv')

In [ ]:
data_

    Season             Club  ...  Won ISL Last season  League table finish
0     2019              ATK  ...                    0                    2
1     2019    Bengaluru FC   ...                    1                    3
2     2019     ChennaiyinFC  ...                    0                    4
3     2019  Kerala Blasters  ...                    0                    7
4     2019        Odisha Fc  ...                    0                    6
5     2019           FC Goa  ...                    0                    1
6     2019            NEUFC  ...                    0                    9
7     2019    Jamshedpur FC  ...                    0                    8
8     2019     Hyderabad FC  ...                    0                   10
9     2019   Mumbai City FC  ...                    0                    5
10    2018              ATK  ...                    0                    6
11    2018    Bengaluru FC   ...                    0                    1
12    2018     ChennaiyinFC  ...                    1                   10
13    2018  Kerala Blasters  ...                    0                    9
14    2018        Odisha Fc  ...                    0                    8
15    2018           FC Goa  ...                    0                    2
16    2018            NEUFC  ...                    0                    4
17    2018    Jamshedpur FC  ...                    0                    5
18    2018     Hyderabad FC  ...                    0                    7
19    2018   Mumbai City FC  ...                    0                    3
20    2017              ATK  ...                    1                    9
21    2017     ChennaiyinFC  ...                    0                    2
22    2017  Kerala Blasters  ...                    0                    7
23    2017        Odisha Fc  ...                    0                    8
24    2017           FC Goa  ...                    0                    3
25    2017            NEUFC  ...                    0                   10
26    2017     Hyderabad FC  ...                    0                    4
27    2017   Mumbai City FC  ...                    0                    7
28    2016              ATK  ...                    0                    4
29    2016     ChennaiyinFC  ...                    1                    7
30    2016  Kerala Blasters  ...                    0                    2
31    2016        Odisha Fc  ...                    0                    3
32    2016           FC Goa  ...                    0                    8
33    2016            NEUFC  ...                    0                    5
34    2016     Hyderabad FC  ...                    0                    6
35    2016   Mumbai City FC  ...                    0                    1
36    2015              ATK  ...                    1                    2
37    2015     ChennaiyinFC  ...                    0                    3
38    2015  Kerala Blasters  ...                    0                    8
39    2015        Odisha Fc  ...                    0                    4
40    2015           FC Goa  ...                    0                    1
41    2015            NEUFC  ...                    0                    5
42    2015     Hyderabad FC  ...                    0                    7
43    2015   Mumbai City FC  ...                    0                    6

[44 rows x 13 columns]

In [ ]:
x = data_.iloc[:,1:-4 ]
x.shape

(44, 8)

In [ ]:
X_2 = data_.iloc[:,-4:-1]
X_2

    Club Value(Million rupees)  Final Played Last season  Won ISL Last season
0                       504.10                         0                    0
1                       443.68                         1                    1
2                       331.21                         0                    0
3                       414.52                         0                    0
4                       364.53                         0                    0
5                       404.10                         1                    0
6                       454.03                         0                    0
7                       314.53                         0                    0
8                       383.27                         0                    0
9                       374.94                         0                    0
10                      477.03                         0                    0
11                      493.67                         1                    0
12                      377.05                         1                    1
13                      362.44                         0                    0
14                      406.19                         0                    0
15                      468.68                         0                    0
16                      479.09                         0                    0
17                      364.55                         0                    0
18                      408.27                         0                    0
19                      429.10                         0                    0
20                      420.77                         1                    1
21                      310.66                         0                    0
22                      302.05                         1                    0
23                      318.70                         0                    0
24                      397.90                         0                    0
25                      422.85                         0                    0
26                      318.70                         0                    0
27                      233.30                         0                    0
28                      516.59                         0                    0
29                      302.36                         1                    1
30                      252.04                         0                    0
31                      335.36                         0                    0
32                      368.69                         1                    0
33                      364.53                         0                    0
34                      441.60                         0                    0
35                      329.11                         0                    0
36                      727.00                         1                    1
37                      333.28                         0                    0
38                      260.38                         1                    0
39                      189.55                         0                    0
40                      368.69                         0                    0
41                      466.69                         0                    0
42                      810.29                         0                    0
43                      572.83                         0                    0

In [ ]:
y = data_.iloc[:, -1]
y

0      2
1      3
2      4
3      7
4      6
5      1
6      9
7      8
8     10
9      5
10     6
11     1
12    10
13     9
14     8
15     2
16     4
17     5
18     7
19     3
20     9
21     2
22     7
23     8
24     3
25    10
26     4
27     7
28     4
29     7
30     2
31     3
32     8
33     5
34     6
35     1
36     2
37     3
38     8
39     4
40     1
41     5
42     7
43     6
Name: League table finish, dtype: int64

In [ ]:
x.join(x, y, how='inner')

               Club  Arrivals  ...  Foreign Players   League table finish
0               ATK        20  ...                 9                    2
1     Bengaluru FC         12  ...                11                    3
2      ChennaiyinFC        11  ...                 7                    4
3   Kerala Blasters        28  ...                 8                    7
4         Odisha Fc        13  ...                 8                    6
5            FC Goa        11  ...                 6                    1
6             NEUFC        19  ...                10                    9
7     Jamshedpur FC        15  ...                 7                    8
8      Hyderabad FC        24  ...                 7                   10
9    Mumbai City FC        14  ...                 7                    5
10              ATK        35  ...                 9                    6
11    Bengaluru FC         19  ...                 9                    1
12     ChennaiyinFC        22  ...                 8                   10
13  Kerala Blasters        24  ...                 7                    9
14        Odisha Fc        20  ...                 8                    8
15           FC Goa        16  ...                 8                    2
16            NEUFC        19  ...                 9                    4
17    Jamshedpur FC        19  ...                 7                    5
18     Hyderabad FC        19  ...                 8                    7
19   Mumbai City FC        20  ...                 7                    3
20              ATK         6  ...                11                    9
21     ChennaiyinFC        23  ...                 8                    2
22  Kerala Blasters         8  ...                10                    7
23        Odisha Fc         8  ...                 9                    8
24           FC Goa        10  ...                10                    3
25            NEUFC        15  ...                11                   10
26     Hyderabad FC        18  ...                10                    4
27   Mumbai City FC         9  ...                 8                    7
28              ATK        23  ...                 9                    4
29     ChennaiyinFC        28  ...                11                    7
30  Kerala Blasters        31  ...                10                    2
31        Odisha Fc        27  ...                11                    3
32           FC Goa        23  ...                10                    8
33            NEUFC        28  ...                12                    5
34     Hyderabad FC        26  ...                11                    6
35   Mumbai City FC        29  ...                11                    1
36              ATK        28  ...                11                    2
37     ChennaiyinFC        30  ...                11                    3
38  Kerala Blasters        25  ...                11                    8
39        Odisha Fc        24  ...                11                    4
40           FC Goa        28  ...                12                    1
41            NEUFC        28  ...                14                    5
42     Hyderabad FC        29  ...                11                    7
43   Mumbai City FC        27  ...                11                    6

[44 rows x 9 columns]

In [ ]:
Y_2018 = y[10:20,]
Y_2018

10     6
11     1
12    10
13     9
14     8
15     2
16     4
17     5
18     7
19     3
Name: League table finish, dtype: int64

In [ ]:
x.shape

(44, 8)

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ColTran = ColumnTransformer(transformers= [('encoder', OneHotEncoder(), [0])], remainder = 'passthrough')
X = np.array(ColTran.fit_transform(x))

In [ ]:
X

array([[ 1.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   , 20.   , 18.   ,  1.   , 31.   ,  6.   ,  4.8  ,
         9.   ],
       [ 0.   ,  1.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   , 12.   , 15.   ,  0.   , 34.   ,  1.   ,  0.5  ,
        11.   ],
       [ 0.   ,  0.   ,  1.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   , 11.   , 15.   ,  0.   , 25.   , 10.   ,  4.6  ,
         7.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  1.   ,  0.   ,
         0.   ,  0.   , 28.   , 20.   ,  1.   , 34.   ,  9.   ,  6.   ,
         8.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  1.   , 13.   , 12.   ,  0.   , 27.   ,  8.   ,  5.6  ,
         8.   ],
       [ 0.   ,  0.   ,  0.   ,  1.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   , 11.   ,  7.   ,  0.   , 26.   ,  2.   ,  3.2  ,
         6.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         1.   ,  0.   , 19.   , 17.   ,  1.   , 30.   ,  4.   ,  6.4  ,
        10.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  1.   ,  0.   ,  0.   ,
         0.   ,  0.   , 15.   , 18.   ,  1.   , 26.   ,  5.   ,  5.   ,
         7.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  1.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   , 24.   ,  6.   ,  1.   , 33.   ,  7.   ,  6.   ,
         7.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  1.   ,
         0.   ,  0.   , 14.   , 15.   ,  0.   , 28.   ,  3.   ,  4.8  ,
         7.   ],
       [ 1.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   , 35.   , 29.   ,  1.   , 33.   ,  9.   ,  4.5  ,
         9.   ],
       [ 0.   ,  1.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   , 19.   , 18.   ,  0.   , 33.   ,  1.   ,  1.   ,
         9.   ],
       [ 0.   ,  0.   ,  1.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   , 22.   , 21.   ,  0.   , 30.   ,  2.   ,  3.25 ,
         8.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  1.   ,  0.   ,
         0.   ,  0.   , 24.   , 21.   ,  1.   , 34.   ,  7.   ,  5.25 ,
         7.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  1.   , 20.   , 19.   ,  1.   , 28.   ,  8.   ,  5.   ,
         8.   ],
       [ 0.   ,  0.   ,  0.   ,  1.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   , 16.   , 15.   ,  0.   , 26.   ,  3.   ,  3.5  ,
         8.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         1.   ,  0.   , 19.   , 24.   ,  1.   , 27.   , 10.   ,  7.   ,
         9.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  1.   ,  0.   ,  0.   ,
         0.   ,  0.   , 19.   , 20.   ,  1.   , 28.   ,  5.   ,  5.   ,
         7.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  1.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   , 19.   , 21.   ,  1.   , 33.   ,  4.   ,  5.75 ,
         8.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  1.   ,
         0.   ,  0.   , 20.   , 23.   ,  0.   , 29.   ,  7.   ,  5.25 ,
         7.   ],
       [ 1.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   ,  6.   , 32.   ,  1.   , 31.   ,  4.   ,  3.   ,
        11.   ],
       [ 0.   ,  0.   ,  1.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   , 23.   ,  8.   ,  1.   , 32.   ,  7.   ,  3.66 ,
         8.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  1.   ,  0.   ,
         0.   ,  0.   ,  8.   , 33.   ,  1.   , 34.   ,  2.   ,  4.66 ,
        10.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  1.   ,  8.   , 27.   ,  1.   , 27.   ,  3.   ,  4.   ,
         9.   ],
       [ 0.   ,  0.   ,  0.   ,  1.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   , 10.   , 29.   ,  1.   , 29.   ,  8.   ,  3.66 ,
        10.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         1.   ,  0.   , 15.   , 30.   ,  1.   , 27.   ,  5.   ,  6.   ,
        11.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  1.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   , 18.   , 39.   ,  1.   , 33.   ,  6.   ,  6.333,
        10.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  1.   ,
         0.   ,  0.   ,  9.   , 26.   ,  0.   , 25.   ,  1.   ,  4.667,
         8.   ],
       [ 1.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   , 23.   , 28.   ,  1.   , 25.   ,  2.   ,  2.5  ,
         9.   ],
       [ 0.   ,  0.   ,  1.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   , 28.   , 28.   ,  0.   , 29.   ,  3.   ,  2.   ,
        11.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  1.   ,  0.   ,
         0.   ,  0.   , 31.   , 28.   ,  1.   , 27.   ,  8.   ,  6.   ,
        10.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  1.   , 27.   , 28.   ,  1.   , 26.   ,  4.   ,  4.5  ,
        11.   ],
       [ 0.   ,  0.   ,  0.   ,  1.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   , 23.   , 27.   ,  0.   , 24.   ,  1.   ,  1.5  ,
        10.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         1.   ,  0.   , 28.   , 34.   ,  1.   , 26.   ,  5.   ,  6.5  ,
        12.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  1.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   , 26.   , 28.   ,  1.   , 25.   ,  7.   ,  6.5  ,
        11.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  1.   ,
         0.   ,  0.   , 29.   , 26.   ,  1.   , 29.   ,  6.   ,  6.5  ,
        11.   ],
       [ 1.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   , 28.   , 26.   ,  0.   , 29.   ,  3.   ,  3.   ,
        11.   ],
       [ 0.   ,  0.   ,  1.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   , 30.   , 33.   ,  0.   , 29.   ,  1.   ,  1.   ,
        11.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  1.   ,  0.   ,
         0.   ,  0.   , 25.   , 29.   ,  1.   , 28.   ,  4.   ,  4.   ,
        11.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  1.   , 24.   , 26.   ,  0.   , 28.   ,  5.   ,  5.   ,
        11.   ],
       [ 0.   ,  0.   ,  0.   ,  1.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   , 28.   , 28.   ,  0.   , 27.   ,  2.   ,  2.   ,
        12.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         1.   ,  0.   , 28.   , 28.   ,  0.   , 28.   ,  8.   ,  8.   ,
        14.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  1.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   , 29.   , 29.   ,  1.   , 26.   ,  6.   ,  6.   ,
        11.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  1.   ,
         0.   ,  0.   , 27.   , 27.   ,  1.   , 26.   ,  7.   ,  7.   ,
        11.   ]])

In [ ]:
X_pd = pd.DataFrame(X)
X_pd

     0    1    2    3    4    5    6   ...    10    11   12    13    14     15    16
0   1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  20.0  18.0  1.0  31.0   6.0  4.800   9.0
1   0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  12.0  15.0  0.0  34.0   1.0  0.500  11.0
2   0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  11.0  15.0  0.0  25.0  10.0  4.600   7.0
3   0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  28.0  20.0  1.0  34.0   9.0  6.000   8.0
4   0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  13.0  12.0  0.0  27.0   8.0  5.600   8.0
5   0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  11.0   7.0  0.0  26.0   2.0  3.200   6.0
6   0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  19.0  17.0  1.0  30.0   4.0  6.400  10.0
7   0.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  15.0  18.0  1.0  26.0   5.0  5.000   7.0
8   0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  24.0   6.0  1.0  33.0   7.0  6.000   7.0
9   0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  14.0  15.0  0.0  28.0   3.0  4.800   7.0
10  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  35.0  29.0  1.0  33.0   9.0  4.500   9.0
11  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  19.0  18.0  0.0  33.0   1.0  1.000   9.0
12  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  22.0  21.0  0.0  30.0   2.0  3.250   8.0
13  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  24.0  21.0  1.0  34.0   7.0  5.250   7.0
14  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  20.0  19.0  1.0  28.0   8.0  5.000   8.0
15  0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  16.0  15.0  0.0  26.0   3.0  3.500   8.0
16  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  19.0  24.0  1.0  27.0  10.0  7.000   9.0
17  0.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  19.0  20.0  1.0  28.0   5.0  5.000   7.0
18  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  19.0  21.0  1.0  33.0   4.0  5.750   8.0
19  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  20.0  23.0  0.0  29.0   7.0  5.250   7.0
20  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   6.0  32.0  1.0  31.0   4.0  3.000  11.0
21  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  23.0   8.0  1.0  32.0   7.0  3.660   8.0
22  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...   8.0  33.0  1.0  34.0   2.0  4.660  10.0
23  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   8.0  27.0  1.0  27.0   3.0  4.000   9.0
24  0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  10.0  29.0  1.0  29.0   8.0  3.660  10.0
25  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  15.0  30.0  1.0  27.0   5.0  6.000  11.0
26  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  18.0  39.0  1.0  33.0   6.0  6.333  10.0
27  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   9.0  26.0  0.0  25.0   1.0  4.667   8.0
28  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  23.0  28.0  1.0  25.0   2.0  2.500   9.0
29  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  28.0  28.0  0.0  29.0   3.0  2.000  11.0
30  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  31.0  28.0  1.0  27.0   8.0  6.000  10.0
31  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  27.0  28.0  1.0  26.0   4.0  4.500  11.0
32  0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  23.0  27.0  0.0  24.0   1.0  1.500  10.0
33  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  28.0  34.0  1.0  26.0   5.0  6.500  12.0
34  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  26.0  28.0  1.0  25.0   7.0  6.500  11.0
35  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  29.0  26.0  1.0  29.0   6.0  6.500  11.0
36  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  28.0  26.0  0.0  29.0   3.0  3.000  11.0
37  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  30.0  33.0  0.0  29.0   1.0  1.000  11.0
38  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  25.0  29.0  1.0  28.0   4.0  4.000  11.0
39  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  24.0  26.0  0.0  28.0   5.0  5.000  11.0
40  0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  28.0  28.0  0.0  27.0   2.0  2.000  12.0
41  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  28.0  28.0  0.0  28.0   8.0  8.000  14.0
42  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  29.0  29.0  1.0  26.0   6.0  6.000  11.0
43  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  27.0  27.0  1.0  26.0   7.0  7.000  11.0

[44 rows x 17 columns]

In [ ]:
X_full = X_pd.join(X_2)
X_full

      0    1  ...  Final Played Last season  Won ISL Last season
0   1.0  0.0  ...                         0                    0
1   0.0  1.0  ...                         1                    1
2   0.0  0.0  ...                         0                    0
3   0.0  0.0  ...                         0                    0
4   0.0  0.0  ...                         0                    0
5   0.0  0.0  ...                         1                    0
6   0.0  0.0  ...                         0                    0
7   0.0  0.0  ...                         0                    0
8   0.0  0.0  ...                         0                    0
9   0.0  0.0  ...                         0                    0
10  1.0  0.0  ...                         0                    0
11  0.0  1.0  ...                         1                    0
12  0.0  0.0  ...                         1                    1
13  0.0  0.0  ...                         0                    0
14  0.0  0.0  ...                         0                    0
15  0.0  0.0  ...                         0                    0
16  0.0  0.0  ...                         0                    0
17  0.0  0.0  ...                         0                    0
18  0.0  0.0  ...                         0                    0
19  0.0  0.0  ...                         0                    0
20  1.0  0.0  ...                         1                    1
21  0.0  0.0  ...                         0                    0
22  0.0  0.0  ...                         1                    0
23  0.0  0.0  ...                         0                    0
24  0.0  0.0  ...                         0                    0
25  0.0  0.0  ...                         0                    0
26  0.0  0.0  ...                         0                    0
27  0.0  0.0  ...                         0                    0
28  1.0  0.0  ...                         0                    0
29  0.0  0.0  ...                         1                    1
30  0.0  0.0  ...                         0                    0
31  0.0  0.0  ...                         0                    0
32  0.0  0.0  ...                         1                    0
33  0.0  0.0  ...                         0                    0
34  0.0  0.0  ...                         0                    0
35  0.0  0.0  ...                         0                    0
36  1.0  0.0  ...                         1                    1
37  0.0  0.0  ...                         0                    0
38  0.0  0.0  ...                         1                    0
39  0.0  0.0  ...                         0                    0
40  0.0  0.0  ...                         0                    0
41  0.0  0.0  ...                         0                    0
42  0.0  0.0  ...                         0                    0
43  0.0  0.0  ...                         0                    0

[44 rows x 20 columns]

In [ ]:
from sklearn.preprocessing import StandardScaler

scale = StandardScaler()
X_Scale = scale.fit_transform(X_full)
X_Scale.shape

(44, 20)

In [ ]:
X_Scale_2018= X_Scale[10:20, :]
X_Scale_2018

array([[ 2.79284801, -0.21821789, -0.35805744, -0.35805744, -0.35805744,
        -0.21821789, -0.35805744, -0.35805744, -0.35805744, -0.35805744,
         1.97760611,  0.75287028,  0.79349205,  1.4495253 ,  1.52796424,
        -0.23046638, -0.54232614, -0.35805744],
       [-0.35805744,  4.58257569, -0.35805744, -0.35805744, -0.35805744,
        -0.21821789, -0.35805744, -0.35805744, -0.35805744, -0.35805744,
        -0.23580359, -0.73443264, -1.26025208,  1.4495253 , -1.51069911,
        -0.23046638,  1.84390889, -0.35805744],
       [-0.35805744, -0.21821789,  2.79284801, -0.35805744, -0.35805744,
        -0.21821789, -0.35805744, -0.35805744, -0.35805744, -0.35805744,
         0.17921073, -0.32880457, -1.26025208,  0.42633097, -1.13086619,
        -0.79382866,  1.84390889,  2.79284801],
       [-0.35805744, -0.21821789, -0.35805744, -0.35805744, -0.35805744,
        -0.21821789,  2.79284801, -0.35805744, -0.35805744, -0.35805744,
         0.45588694, -0.32880457,  0.79349205,  1.79059008,  0.7682984 ,
        -1.35719093, -0.54232614, -0.35805744],
       [-0.35805744, -0.21821789, -0.35805744, -0.35805744, -0.35805744,
        -0.21821789, -0.35805744, -0.35805744, -0.35805744,  2.79284801,
        -0.09746548, -0.59922329,  0.79349205, -0.25579858,  1.14813132,
        -0.79382866, -0.54232614, -0.35805744],
       [-0.35805744, -0.21821789, -0.35805744,  2.79284801, -0.35805744,
        -0.21821789, -0.35805744, -0.35805744, -0.35805744, -0.35805744,
        -0.65081791, -1.14006071, -1.26025208, -0.93792814, -0.75103327,
        -0.79382866, -0.54232614, -0.35805744],
       [-0.35805744, -0.21821789, -0.35805744, -0.35805744, -0.35805744,
        -0.21821789, -0.35805744, -0.35805744,  2.79284801, -0.35805744,
        -0.23580359,  0.0768235 ,  0.79349205, -0.59686336,  1.90779716,
        -0.23046638, -0.54232614, -0.35805744],
       [-0.35805744, -0.21821789, -0.35805744, -0.35805744, -0.35805744,
         4.58257569, -0.35805744, -0.35805744, -0.35805744, -0.35805744,
        -0.23580359, -0.46401393,  0.79349205, -0.25579858,  0.00863257,
        -1.35719093, -0.54232614, -0.35805744],
       [-0.35805744, -0.21821789, -0.35805744, -0.35805744,  2.79284801,
        -0.21821789, -0.35805744, -0.35805744, -0.35805744, -0.35805744,
        -0.23580359, -0.32880457,  0.79349205,  1.4495253 , -0.37120035,
        -0.79382866, -0.54232614, -0.35805744],
       [-0.35805744, -0.21821789, -0.35805744, -0.35805744, -0.35805744,
        -0.21821789, -0.35805744,  2.79284801, -0.35805744, -0.35805744,
        -0.09746548, -0.05838586, -1.26025208,  0.08526619,  0.7682984 ,
        -1.35719093, -0.54232614, -0.35805744]])

## **Training Part**

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size= 0.2, random_state=0)

In [ ]:
X_train.shape

(35, 17)

In [ ]:
X_test.shape

(9, 17)

In [ ]:
Y_train.shape

(35,)

In [ ]:
Y_test.shape

(9,)

In [ ]:
import tensorflow as tf

In [ ]:
import tensorflow as tf
model = tf.keras.models.Sequential([
                                   # First Hidden Layer
                                   tf.keras.layers.Dense(units=16,input_dim = 20, activation='relu'),
                                   tf.keras.layers.Dense(units= 18, activation='relu'),
                                   
                                   
                                   # Output Layer 
                                   tf.keras.layers.Dense(units=1)

])

In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_3 (Dense)              (None, 16)                288
_________________________________________________________________
dense_4 (Dense)              (None, 18)                306
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 19
=================================================================
Total params: 613
Trainable params: 613
Non-trainable params: 0
_________________________________________________________________

In [ ]:
model.compile(
    optimizer= 'adam',
    loss = 'mean_squared_error'
)

In [ ]:
history = model.fit(X_train, Y_train , steps_per_epoch=10, epochs=300, verbose=1)

Epoch 1/275
10/10 [==============================] - 0s 2ms/step - loss: 3.2308
Epoch 2/275
10/10 [==============================] - 0s 2ms/step - loss: 0.7770
Epoch 3/275
10/10 [==============================] - 0s 2ms/step - loss: 1.7148
Epoch 4/275
10/10 [==============================] - 0s 2ms/step - loss: 1.0711
Epoch 5/275
10/10 [==============================] - 0s 2ms/step - loss: 0.9563
Epoch 6/275
10/10 [==============================] - 0s 2ms/step - loss: 0.9747
Epoch 7/275
10/10 [==============================] - 0s 2ms/step - loss: 0.6532
Epoch 8/275
10/10 [==============================] - 0s 2ms/step - loss: 0.9162
Epoch 9/275
10/10 [==============================] - 0s 2ms/step - loss: 0.7147
Epoch 10/275
10/10 [==============================] - 0s 2ms/step - loss: 0.7505
Epoch 11/275
10/10 [==============================] - 0s 2ms/step - loss: 0.6428
Epoch 12/275
10/10 [==============================] - 0s 2ms/step - loss: 0.5683
Epoch 13/275
10/10 [==============================] - 0s 2ms/step - loss: 0.4477
Epoch 14/275
10/10 [==============================] - 0s 2ms/step - loss: 0.5197
Epoch 15/275
10/10 [==============================] - 0s 2ms/step - loss: 0.4810
Epoch 16/275
10/10 [==============================] - 0s 2ms/step - loss: 0.4609
Epoch 17/275
10/10 [==============================] - 0s 2ms/step - loss: 0.4087
Epoch 18/275
10/10 [==============================] - 0s 2ms/step - loss: 0.3946
Epoch 19/275
10/10 [==============================] - 0s 2ms/step - loss: 0.4098
Epoch 20/275
10/10 [==============================] - 0s 2ms/step - loss: 0.3028
Epoch 21/275
10/10 [==============================] - 0s 2ms/step - loss: 0.4462
Epoch 22/275
10/10 [==============================] - 0s 2ms/step - loss: 0.2837
Epoch 23/275
10/10 [==============================] - 0s 2ms/step - loss: 0.2805
Epoch 24/275
10/10 [==============================] - 0s 2ms/step - loss: 0.3886
Epoch 25/275
10/10 [==============================] - 0s 2ms/step - loss: 0.2226
Epoch 26/275
10/10 [==============================] - 0s 2ms/step - loss: 0.2740
Epoch 27/275
10/10 [==============================] - 0s 2ms/step - loss: 0.2536
Epoch 28/275
10/10 [==============================] - 0s 2ms/step - loss: 0.2240
Epoch 29/275
10/10 [==============================] - 0s 2ms/step - loss: 0.2329
Epoch 30/275
10/10 [==============================] - 0s 2ms/step - loss: 0.2145
Epoch 31/275
10/10 [==============================] - 0s 2ms/step - loss: 0.2709
Epoch 32/275
10/10 [==============================] - 0s 2ms/step - loss: 0.1822
Epoch 33/275
10/10 [==============================] - 0s 2ms/step - loss: 0.1901
Epoch 34/275
10/10 [==============================] - 0s 2ms/step - loss: 0.1647
Epoch 35/275
10/10 [==============================] - 0s 2ms/step - loss: 0.1847
Epoch 36/275
10/10 [==============================] - 0s 2ms/step - loss: 0.1742
Epoch 37/275
10/10 [==============================] - 0s 2ms/step - loss: 0.1416
Epoch 38/275
10/10 [==============================] - 0s 2ms/step - loss: 0.1547
Epoch 39/275
10/10 [==============================] - 0s 2ms/step - loss: 0.1372
Epoch 40/275
10/10 [==============================] - 0s 2ms/step - loss: 0.1149
Epoch 41/275
10/10 [==============================] - 0s 2ms/step - loss: 0.1469
Epoch 42/275
10/10 [==============================] - 0s 2ms/step - loss: 0.1431
Epoch 43/275
10/10 [==============================] - 0s 2ms/step - loss: 0.1049
Epoch 44/275
10/10 [==============================] - 0s 2ms/step - loss: 0.1031
Epoch 45/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0949
Epoch 46/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0947
Epoch 47/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0868
Epoch 48/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0797
Epoch 49/275
10/10 [==============================] - 0s 2ms/step - loss: 0.1043
Epoch 50/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0973
Epoch 51/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0755
Epoch 52/275
10/10 [==============================] - 0s 3ms/step - loss: 0.0757
Epoch 53/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0739
Epoch 54/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0638
Epoch 55/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0631
Epoch 56/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0734
Epoch 57/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0544
Epoch 58/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0661
Epoch 59/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0586
Epoch 60/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0518
Epoch 61/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0479
Epoch 62/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0592
Epoch 63/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0449
Epoch 64/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0472
Epoch 65/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0438
Epoch 66/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0400
Epoch 67/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0367
Epoch 68/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0418
Epoch 69/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0373
Epoch 70/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0362
Epoch 71/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0443
Epoch 72/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0310
Epoch 73/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0301
Epoch 74/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0390
Epoch 75/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0249
Epoch 76/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0211
Epoch 77/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0395
Epoch 78/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0247
Epoch 79/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0230
Epoch 80/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0229
Epoch 81/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0230
Epoch 82/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0222
Epoch 83/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0217
Epoch 84/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0239
Epoch 85/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0128
Epoch 86/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0229
Epoch 87/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0222
Epoch 88/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0082
Epoch 89/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0232
Epoch 90/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0150
Epoch 91/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0148
Epoch 92/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0141
Epoch 93/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0174
Epoch 94/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0070
Epoch 95/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0147
Epoch 96/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0180
Epoch 97/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0067
Epoch 98/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0162
Epoch 99/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0105
Epoch 100/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0101
Epoch 101/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0105
Epoch 102/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0154
Epoch 103/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0027
Epoch 104/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0118
Epoch 105/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0080
Epoch 106/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0128
Epoch 107/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0085
Epoch 108/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0080
Epoch 109/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0074
Epoch 110/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0076
Epoch 111/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0079
Epoch 112/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0063
Epoch 113/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0065
Epoch 114/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0088
Epoch 115/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0062
Epoch 116/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0097
Epoch 117/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0061
Epoch 118/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0061
Epoch 119/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0052
Epoch 120/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0070
Epoch 121/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0038
Epoch 122/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0053
Epoch 123/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0094
Epoch 124/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0021
Epoch 125/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0073
Epoch 126/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0047
Epoch 127/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0044
Epoch 128/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0044
Epoch 129/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0056
Epoch 130/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0060
Epoch 131/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0043
Epoch 132/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0028
Epoch 133/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0038
Epoch 134/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0047
Epoch 135/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0037
Epoch 136/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0034
Epoch 137/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0033
Epoch 138/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0033
Epoch 139/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0033
Epoch 140/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0045
Epoch 141/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0042
Epoch 142/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0028
Epoch 143/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0026
Epoch 144/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0030
Epoch 145/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0026
Epoch 146/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0026
Epoch 147/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0027
Epoch 148/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0023
Epoch 149/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0031
Epoch 150/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0022
Epoch 151/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0035
Epoch 152/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0023
Epoch 153/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0021
Epoch 154/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0031
Epoch 155/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0021
Epoch 156/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0013
Epoch 157/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0019
Epoch 158/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0023
Epoch 159/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0026
Epoch 160/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0018
Epoch 161/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0017
Epoch 162/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0017
Epoch 163/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0016
Epoch 164/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0018
Epoch 165/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0010
Epoch 166/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0014
Epoch 167/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0013
Epoch 168/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0021
Epoch 169/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0012
Epoch 170/275
10/10 [==============================] - 0s 2ms/step - loss: 8.4966e-04
Epoch 171/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0019
Epoch 172/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0011
Epoch 173/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0010
Epoch 174/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0011
Epoch 175/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0015
Epoch 176/275
10/10 [==============================] - 0s 3ms/step - loss: 0.0011
Epoch 177/275
10/10 [==============================] - 0s 2ms/step - loss: 8.5665e-04
Epoch 178/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0012
Epoch 179/275
10/10 [==============================] - 0s 2ms/step - loss: 8.2264e-04
Epoch 180/275
10/10 [==============================] - 0s 2ms/step - loss: 8.5875e-04
Epoch 181/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0013
Epoch 182/275
10/10 [==============================] - 0s 2ms/step - loss: 7.2916e-04
Epoch 183/275
10/10 [==============================] - 0s 2ms/step - loss: 9.7201e-04
Epoch 184/275
10/10 [==============================] - 0s 2ms/step - loss: 1.2390e-04
Epoch 185/275
10/10 [==============================] - 0s 2ms/step - loss: 0.0013
Epoch 186/275
10/10 [==============================] - 0s 2ms/step - loss: 4.6795e-04
Epoch 187/275
10/10 [==============================] - 0s 2ms/step - loss: 8.3993e-04
Epoch 188/275
10/10 [==============================] - 0s 2ms/step - loss: 5.9355e-04
Epoch 189/275
10/10 [==============================] - 0s 2ms/step - loss: 5.9264e-04
Epoch 190/275
10/10 [==============================] - 0s 2ms/step - loss: 5.8925e-04
Epoch 191/275
10/10 [==============================] - 0s 2ms/step - loss: 5.2868e-04
Epoch 192/275
10/10 [==============================] - 0s 2ms/step - loss: 5.7518e-04
Epoch 193/275
10/10 [==============================] - 0s 2ms/step - loss: 4.5787e-04
Epoch 194/275
10/10 [==============================] - 0s 2ms/step - loss: 6.4351e-04
Epoch 195/275
10/10 [==============================] - 0s 2ms/step - loss: 4.1265e-04
Epoch 196/275
10/10 [==============================] - 0s 2ms/step - loss: 4.1686e-04
Epoch 197/275
10/10 [==============================] - 0s 2ms/step - loss: 8.4498e-04
Epoch 198/275
10/10 [==============================] - 0s 2ms/step - loss: 4.1315e-04
Epoch 199/275
10/10 [==============================] - 0s 3ms/step - loss: 4.9645e-04
Epoch 200/275
10/10 [==============================] - 0s 2ms/step - loss: 2.8957e-04
Epoch 201/275
10/10 [==============================] - 0s 2ms/step - loss: 5.8416e-04
Epoch 202/275
10/10 [==============================] - 0s 2ms/step - loss: 1.5220e-04
Epoch 203/275
10/10 [==============================] - 0s 2ms/step - loss: 6.3720e-04
Epoch 204/275
10/10 [==============================] - 0s 2ms/step - loss: 3.4642e-04
Epoch 205/275
10/10 [==============================] - 0s 2ms/step - loss: 9.5716e-05
Epoch 206/275
10/10 [==============================] - 0s 3ms/step - loss: 5.1061e-04
Epoch 207/275
10/10 [==============================] - 0s 2ms/step - loss: 3.0599e-04
Epoch 208/275
10/10 [==============================] - 0s 2ms/step - loss: 3.6461e-04
Epoch 209/275
10/10 [==============================] - 0s 2ms/step - loss: 1.9324e-04
Epoch 210/275
10/10 [==============================] - 0s 2ms/step - loss: 4.4237e-04
Epoch 211/275
10/10 [==============================] - 0s 2ms/step - loss: 2.4489e-04
Epoch 212/275
10/10 [==============================] - 0s 2ms/step - loss: 2.4147e-04
Epoch 213/275
10/10 [==============================] - 0s 2ms/step - loss: 2.9073e-04
Epoch 214/275
10/10 [==============================] - 0s 2ms/step - loss: 2.0738e-04
Epoch 215/275
10/10 [==============================] - 0s 2ms/step - loss: 7.0584e-05
Epoch 216/275
10/10 [==============================] - 0s 2ms/step - loss: 3.3662e-04
Epoch 217/275
10/10 [==============================] - 0s 2ms/step - loss: 1.9179e-04
Epoch 218/275
10/10 [==============================] - 0s 2ms/step - loss: 1.9261e-04
Epoch 219/275
10/10 [==============================] - 0s 2ms/step - loss: 2.7246e-04
Epoch 220/275
10/10 [==============================] - 0s 2ms/step - loss: 2.0477e-04
Epoch 221/275
10/10 [==============================] - 0s 2ms/step - loss: 1.0810e-05
Epoch 222/275
10/10 [==============================] - 0s 2ms/step - loss: 2.7777e-04
Epoch 223/275
10/10 [==============================] - 0s 2ms/step - loss: 6.3691e-05
Epoch 224/275
10/10 [==============================] - 0s 2ms/step - loss: 1.3073e-04
Epoch 225/275
10/10 [==============================] - 0s 2ms/step - loss: 2.1534e-04
Epoch 226/275
10/10 [==============================] - 0s 2ms/step - loss: 1.1504e-04
Epoch 227/275
10/10 [==============================] - 0s 2ms/step - loss: 1.1633e-04
Epoch 228/275
10/10 [==============================] - 0s 2ms/step - loss: 1.1705e-04
Epoch 229/275
10/10 [==============================] - 0s 2ms/step - loss: 1.8962e-04
Epoch 230/275
10/10 [==============================] - 0s 2ms/step - loss: 6.7986e-05
Epoch 231/275
10/10 [==============================] - 0s 2ms/step - loss: 1.2249e-04
Epoch 232/275
10/10 [==============================] - 0s 2ms/step - loss: 8.6098e-05
Epoch 233/275
10/10 [==============================] - 0s 2ms/step - loss: 8.3546e-05
Epoch 234/275
10/10 [==============================] - 0s 2ms/step - loss: 9.2841e-05
Epoch 235/275
10/10 [==============================] - 0s 2ms/step - loss: 7.7357e-05
Epoch 236/275
10/10 [==============================] - 0s 2ms/step - loss: 1.4248e-04
Epoch 237/275
10/10 [==============================] - 0s 2ms/step - loss: 4.0439e-05
Epoch 238/275
10/10 [==============================] - 0s 2ms/step - loss: 3.7998e-05
Epoch 239/275
10/10 [==============================] - 0s 2ms/step - loss: 1.3214e-04
Epoch 240/275
10/10 [==============================] - 0s 2ms/step - loss: 3.8588e-05
Epoch 241/275
10/10 [==============================] - 0s 2ms/step - loss: 5.2161e-05
Epoch 242/275
10/10 [==============================] - 0s 2ms/step - loss: 9.7138e-05

In [ ]:
model.save('/content/drive/My Drive/Machine learning')

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/training/tracking/tracking.py:111: Model.state_updates (from tensorflow.python.keras.engine.training) is deprecated and will be removed in a future version.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/training/tracking/tracking.py:111: Layer.updates (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
INFO:tensorflow:Assets written to: /content/drive/My Drive/Machine learning/assets

## **Testing**

In [ ]:
from tensorflow import keras
model_ISL = keras.models.load_model('/content/drive/My Drive/Machine learning/Isl2/')

In [ ]:
Y_predict_ATK = model_ISL.predict(scale.transform([[1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 8., 3.,  0.,
        29.,  2., 4.3, 8.,460.34,  1.,  1.]]))
Y_predict_ATK

array([[4.986812]], dtype=float32)

In [ ]:
Y_predict_ATK = model_ISL.predict(scale.transform([[1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 8., 3.,  0.,
        29.,  2., 4.3, 8.,460.34,  1.,  1.]]))
Y_predict_ATK

array([[4.986812]], dtype=float32)

In [ ]:
Y_predict_BFC = model_ISL.predict(scale.transform([[0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 13., 12.,  0.,
        32.,  3., 1.66, 7.,437.43,  0.,  0.]]))
Y_predict_BFC

array([[0.56777054]], dtype=float32)

In [ ]:
Y_predict_CFC = model_ISL.predict(scale.transform([[ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 12.,  9.,  1.,
        28.,  4., 4.5,  7.,383.37,  1.,  1.]]))
Y_predict_CFC

array([[11.704152]], dtype=float32)

In [ ]:
Y_predict_KBFC = model_ISL.predict(scale.transform([[0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0., 19., 26.,  1.,
        31.,  7.,6.166,  7.,539.5,  0.,  0.]]))
Y_predict_KBFC

array([[7.9786263]], dtype=float32)

In [ ]:
Y_predict_OFC = model_ISL.predict(scale.transform([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1., 23., 12.,  1.,
        35.,  6., 5.66, 7., 410.35, 0.,  0.]]))
Y_predict_OFC

array([[5.741554]], dtype=float32)

In [ ]:
Y_predict_FCGoa = model_ISL.predict(scale.transform([[ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0., 17., 15.,  1.,
        30.,  1., 2.833, 6., 368.69,  0.,  0.]]))
Y_predict_FCGoa

array([[1.4994646]], dtype=float32)

In [ ]:
Y_predict_NEUFC = model_ISL.predict(scale.transform([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0., 21., 12.,  1.,
        30.,  9.,6.833,  7.,374.94,  0.,  0.]]))
Y_predict_NEUFC

array([[8.004615]], dtype=float32)

In [ ]:
Y_predict_JFC = model_ISL.predict(scale.transform([[ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0., 22., 12.,  1.,
        34.,  8., 6, 7.,343.7,  0.,  0.]]))
Y_predict_JFC

array([[4.4777203]], dtype=float32)

In [ ]:
Y_predict_HFC = model_ISL.predict(scale.transform([[  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0., 20., 18.,  1.,
        33., 10.,6.67,  7.,366.61,  0.,  0.]]))
Y_predict_HFC

array([[8.58872]], dtype=float32)

In [ ]:
Y_predict_MCFC = model_ISL.predict(scale.transform([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0., 19., 20.,  1.,
        28.,  5.,4.83,  7.,443.7,  0.,  0.]]))
Y_predict_MCFC

array([[5.009756]], dtype=float32)

In [ ]:
Y_predict_EBFC = model_ISL.predict(scale.transform([[0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 35., 19.,  1.,
        36.,  0, 0, 7.,458.26,  0.,  0.]]))
Y_predict_EBFC

array([[7.4755044]], dtype=float32)

In [ ]:
ISL_clubs = ['ATK MohunBagan', 'Kerala Blasters', 'Bengaluru FC', 'Chennaiyin Fc', 'Odisha FC', 'NEUFC', 'SC East Bengal','FC Goa', 'Hyderabad FC', 'Jamshedpur FC', 'Mumbai City FC' ]
Position = [Y_predict_ATK,  Y_predict_KBFC,  Y_predict_BFC, Y_predict_CFC,Y_predict_OFC,Y_predict_NEUFC, Y_predict_EBFC,Y_predict_FCGoa,Y_predict_HFC,Y_predict_JFC,  Y_predict_MCFC ]
p = np.round(Position)
ISL = {'Club': ISL_clubs, 'Position':list(p)}
ISL

{'Club': ['ATK MohunBagan',
  'Kerala Blasters',
  'Bengaluru FC',
  'Chennaiyin Fc',
  'Odisha FC',
  'NEUFC',
  'SC East Bengal',
  'FC Goa',
  'Hyderabad FC',
  'Jamshedpur FC',
  'Mumbai City FC'],
 'Position': [array([[5.]], dtype=float32),
  array([[8.]], dtype=float32),
  array([[1.]], dtype=float32),
  array([[12.]], dtype=float32),
  array([[6.]], dtype=float32),
  array([[8.]], dtype=float32),
  array([[7.]], dtype=float32),
  array([[1.]], dtype=float32),
  array([[9.]], dtype=float32),
  array([[4.]], dtype=float32),
  array([[5.]], dtype=float32)]}

In [ ]:
ISL_20_table = pd.DataFrame.from_dict(ISL)
ISL_20_table.sort_values('Position')

               Club  Position
2      Bengaluru FC   [[1.0]]
7            FC Goa   [[1.0]]
9     Jamshedpur FC   [[4.0]]
0    ATK MohunBagan   [[5.0]]
10   Mumbai City FC   [[5.0]]
4         Odisha FC   [[6.0]]
6    SC East Bengal   [[7.0]]
1   Kerala Blasters   [[8.0]]
5             NEUFC   [[8.0]]
8      Hyderabad FC   [[9.0]]
3     Chennaiyin Fc  [[12.0]]